"""
Test FastAPI endpoints with real medical note images.
This script tests both the SOAP note generation and medical code generation endpoints
using actual image files.
"""
import sys
import os
from pathlib import Path

# Configure UTF-8 encoding for Windows console
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi.testclient import TestClient
from app.main import app
from app.services.ocr_service import OCRService

# Get project root
PROJECT_ROOT = Path(__file__).parent.parent

def test_soap_generation_with_sample_note():
    """Test SOAP note generation with sample_note.png"""
    print("\n" + "="*80)
    print("TEST 1: SOAP Note Generation with sample_note.png")
    print("="*80)
    
    client = TestClient(app)
    image_path = PROJECT_ROOT / "sample_note.png"
    
    if not image_path.exists():
        print(f"[ERROR] Image not found at {image_path}")
        return False
    
    # First, extract and display OCR text
    ocr_service = OCRService()
    with open(image_path, "rb") as img_file:
        ocr_text = ocr_service.extract_text(img_file.read(), "image/png")
    
    print(f"\n--- OCR Extracted Text ---")
    print(ocr_text)
    print("--- End OCR Text ---\n")
    
    with open(image_path, "rb") as img_file:
        response = client.post(
            "/api/v1/medical/generate-soap-upload",
            files={"file": ("sample_note.png", img_file, "image/png")},
            data={"patient_id": "P001", "provider": "aws"}
        )
    
    print(f"Status Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print("\n[SUCCESS] Response received:")
        print(f"\nPatient ID: {data.get('patient_id')}")
        print(f"Provider: {data.get('provider')}")
        print(f"\nSOAP Note:")
        soap = data.get('soap_note', {})
        print(f"  Subjective: {soap.get('subjective')}")
        print(f"  Objective: {soap.get('objective')}")
        print(f"  Assessment: {soap.get('assessment')}")
        print(f"  Plan: {soap.get('plan')}")
        print(f"  Generated by AI: {soap.get('generated_by_ai')}")
        print(f"  AI Provider: {soap.get('ai_provider')}")
        return True, ocr_text
    else:
        print(f"\n[FAILED] Error: {response.text}")
        return False, ocr_text


def test_soap_generation_with_realistic_note():
    """Test SOAP note generation with realistic_note.png"""
    print("\n" + "="*80)
    print("TEST 2: SOAP Note Generation with realistic_note.png")
    print("="*80)
    
    client = TestClient(app)
    image_path = PROJECT_ROOT / "realistic_note.png"
    
    if not image_path.exists():
        print(f"[ERROR] Image not found at {image_path}")
        return False
    
    # First, extract and display OCR text
    ocr_service = OCRService()
    with open(image_path, "rb") as img_file:
        ocr_text = ocr_service.extract_text(img_file.read(), "image/png")
    
    print(f"\n--- OCR Extracted Text ---")
    print(ocr_text)
    print("--- End OCR Text ---\n")
    
    with open(image_path, "rb") as img_file:
        response = client.post(
            "/api/v1/medical/generate-soap-upload",
            files={"file": ("realistic_note.png", img_file, "image/png")},
            data={"patient_id": "P002", "provider": "aws"}
        )
    
    print(f"Status Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print("\n[SUCCESS] Response received:")
        print(f"\nPatient ID: {data.get('patient_id')}")
        print(f"Provider: {data.get('provider')}")
        print(f"\nSOAP Note:")
        soap = data.get('soap_note', {})
        print(f"  Subjective: {soap.get('subjective')}")
        print(f"  Objective: {soap.get('objective')}")
        print(f"  Assessment: {soap.get('assessment')}")
        print(f"  Plan: {soap.get('plan')}")
        print(f"  Generated by AI: {soap.get('generated_by_ai')}")
        print(f"  AI Provider: {soap.get('ai_provider')}")
        return True, ocr_text
    else:
        print(f"\n[FAILED] Error: {response.text}")
        return False, ocr_text


def test_medical_codes_with_sample_note():
    """Test medical code generation with sample_note.png"""
    print("\n" + "="*80)
    print("TEST 3: Medical Code Generation with sample_note.png")
    print("="*80)
    
    client = TestClient(app)
    image_path = PROJECT_ROOT / "sample_note.png"
    
    if not image_path.exists():
        print(f"[ERROR] Image not found at {image_path}")
        return False
    
    with open(image_path, "rb") as img_file:
        response = client.post(
            "/api/v1/medical/generate-codes-upload",
            files={"file": ("sample_note.png", img_file, "image/png")},
            data={"patient_id": "P001", "provider": "aws"}
        )
    
    print(f"\nStatus Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print("\n[SUCCESS] Response received:")
        print(f"\nPatient ID: {data.get('patient_id')}")
        print(f"Provider: {data.get('provider')}")
        print(f"\nMedical Codes:")
        codes = data.get('medical_codes', {})
        
        icd_codes = codes.get('icd_codes', [])
        cpt_codes = codes.get('cpt_codes', [])
        
        print(f"\n  ICD-10 Codes ({len(icd_codes)}):")
        for code in icd_codes:
            print(f"    - {code.get('code')}: {code.get('description')}")
        
        print(f"\n  CPT Codes ({len(cpt_codes)}):")
        for code in cpt_codes:
            print(f"    - {code.get('code')}: {code.get('description')}")
        
        print(f"\n  Generated by AI: {codes.get('generated_by_ai')}")
        print(f"  AI Provider: {codes.get('ai_provider')}")
        return True
    else:
        print(f"\n[FAILED] Error: {response.text}")
        return False


def test_medical_codes_with_realistic_note():
    """Test medical code generation with realistic_note.png"""
    print("\n" + "="*80)
    print("TEST 4: Medical Code Generation with realistic_note.png")
    print("="*80)
    
    client = TestClient(app)
    image_path = PROJECT_ROOT / "realistic_note.png"
    
    if not image_path.exists():
        print(f"[ERROR] Image not found at {image_path}")
        return False
    
    with open(image_path, "rb") as img_file:
        response = client.post(
            "/api/v1/medical/generate-codes-upload",
            files={"file": ("realistic_note.png", img_file, "image/png")},
            data={"patient_id": "P002", "provider": "aws"}
        )
    
    print(f"\nStatus Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print("\n[SUCCESS] Response received:")
        print(f"\nPatient ID: {data.get('patient_id')}")
        print(f"Provider: {data.get('provider')}")
        print(f"\nMedical Codes:")
        codes = data.get('medical_codes', {})
        
        icd_codes = codes.get('icd_codes', [])
        cpt_codes = codes.get('cpt_codes', [])
        
        print(f"\n  ICD-10 Codes ({len(icd_codes)}):")
        for code in icd_codes:
            print(f"    - {code.get('code')}: {code.get('description')}")
        
        print(f"\n  CPT Codes ({len(cpt_codes)}):")
        for code in cpt_codes:
            print(f"    - {code.get('code')}: {code.get('description')}")
        
        print(f"\n  Generated by AI: {codes.get('generated_by_ai')}")
        print(f"  AI Provider: {codes.get('ai_provider')}")
        return True
    else:
        print(f"\n[FAILED] Error: {response.text}")
        return False


def main():
    """Run all tests"""
    print("\n" + "=" * 80)
    print("FASTAPI ENDPOINT TESTING WITH REAL MEDICAL NOTE IMAGES")
    print("=" * 80)
    
    results = []
    ocr_results = {}
    
    # Run all tests
    result1 = test_soap_generation_with_sample_note()
    results.append(("SOAP with sample_note.png", result1[0]))
    ocr_results["sample_note"] = result1[1]
    
    result2 = test_soap_generation_with_realistic_note()
    results.append(("SOAP with realistic_note.png", result2[0]))
    ocr_results["realistic_note"] = result2[1]
    
    results.append(("Medical Codes with sample_note.png", test_medical_codes_with_sample_note()))
    results.append(("Medical Codes with realistic_note.png", test_medical_codes_with_realistic_note()))
    
    # Print summary
    print("\n" + "="*80)
    print("TEST SUMMARY")
    print("="*80)
    
    passed = sum(1 for _, result in results if result)
    total = len(results)
    
    for test_name, result in results:
        status = "[PASS]" if result else "[FAIL]"
        print(f"{status}: {test_name}")
    
    print(f"\nTotal: {passed}/{total} tests passed")
    
    if passed == total:
        print("\nAll tests passed successfully!")
        return 0
    else:
        print(f"\nWarning: {total - passed} test(s) failed")
        return 1


if __name__ == "__main__":
    exit(main())
